### ISSUE TITLE
Is it available?

### ISSUE THREAD

**Issue by zuohuadong** [polarissolutions/webhdfs-client#1]
Will it stay updated?

**Comment by jcgillespie** [comment]
Yes, it is available. https://www.npmjs.com/package/@polarissolutions/webhdfs-client

We accept issues and pull requests if there's something you need.

**Comment by zuohuadong** [comment]
Any documentation?

**Comment by zuohuadong** [comment]
@jcgillespie Any documentation?

**Comment by jcgillespie** [comment]
At this point, just the code itself and the TypeScript definitions in it, but we'd accept a PR if you wanted to contribute! 👍
