### ISSUE TITLE
how to read file?

### ISSUE THREAD

**Issue by zuohuadong** [polarissolutions/webhdfs-client#3]
```
        let datas:string = '';
        client.OpenFile(hdfsPath)
            .on('datas', chunk  => { 
                datas += chunk
            })
            .on('complete', assert)
            .on ('end',()=> {
                console.log(1,datas)
            })
            .pipe(outStream);
```

I want to  read a file .

![image](https://user-images.githubusercontent.com/11203929/46064412-df985d00-c1a1-11e8-9668-3a791028dc92.png)

**Comment by jcgillespie** [comment]
Have a look at the `Can roundtrip a file` spec in `integration.spec.ts` [link](https://github.com/polarissolutions/webhdfs-client/blob/master/__tests__/integration.spec.ts#L34) 

In your snippet, you need to provide an implementation of `assert()` that accepts the file stream. Here's an example from the integration test,

``` let outStream = new sb.WritableStreamBuffer();
        client.OpenFile(hdfsPath)
            .on('complete', assert)
            .pipe(outStream);

        function assert(): void {
            outStream.end();
            let actual = outStream.getContentsAsString();

            expect(actual).toEqual(expected);
            done();
        }
```

**Comment by zuohuadong** [comment]
thanks
